name: Auto-merge Dependabot PRs
on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2.2.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: auto-merge conditions
        id: auto-merge
        if: ${{(contains('direct:development,indirect:development,direct:production,indirect:production', steps.dependabot-metadata.outputs.dependency-type) && steps.dependabot-metadata.outputs.update-type == 'version-update:semver-patch') || (contains('direct:development,indirect:development', steps.dependabot-metadata.outputs.dependency-type) && steps.dependabot-metadata.outputs.update-type == 'version-update:semver-minor')}}
        run: echo "auto-merge conditions satisfied"
      - name: auto-merge PR
        if: ${{ steps.auto-merge.conclusion == 'success' }}
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
